//
//  ChordLibrary.swift
//  Chord Finder
//
//  Created by Jason Cardwell on 8/31/17.
//  Copyright (c) 2017 Moondeer Studios. All rights reserved.
//
import Foundation

public final class ChordLibrary {

  /// A collection of all available chords indexed by chroma.
  public static let chords: [Chroma:Set<Chord>] = {

    // Create an empty dictionary.
    var chords: [Chroma:Set<Chord>] = [:]

    // Iterate through the twelve chroma values.
    for chroma in (0 ..< 12).map(Chroma.init(rawValue:)) {

      // Insert the set of chords generated by mapping `chroma` onto all chord patterns.
      chords[chroma] = Set(ChordPattern.all.map { Chord(root: chroma, pattern: $0) })

    }

    return chords

  }()

}
